/* Generated by RuntimeBrowser
   Image: /usr/lib/libactivator.dylib
 */

@interface _LAAlertController : NSObject <UIAlertViewDelegate> {
    UIAlertController * _ac;
    UIAlertView * _av;
    <_LAAlertControllerDelegate> * _retainedDelegate;
    _LAAlertController * _retainedSelf;
    NSArray * buttonTitles;
    <_LAAlertControllerDelegate> * delegate;
    NSString * message;
    NSString * textFieldTitle;
    NSString * textFieldValue;
    NSString * title;
}

@property (nonatomic, copy) NSArray *buttonTitles;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <_LAAlertControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *message;
@property (readonly) Class superclass;
@property (nonatomic) NSString *textFieldTitle;
@property (nonatomic, copy) NSString *textFieldValue;
@property (nonatomic, copy) NSString *title;

- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)buttonTitles;
- (void)dealloc;
- (id)delegate;
- (void)dismiss;
- (id)message;
- (void)setButtonTitles:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setMessage:(id)arg1;
- (void)setTextFieldTitle:(id)arg1;
- (void)setTextFieldValue:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)showInViewController:(id)arg1;
- (id)textFieldTitle;
- (id)textFieldValue;
- (id)title;

@end
