/* Generated by RuntimeBrowser
   Image: /usr/lib/libactivator.dylib
 */

@interface LAListenerSettingsViewController : LASettingsViewController {
    NSMutableDictionary * _compatibleEvents;
    NSString * _eventMode;
    NSMutableDictionary * _events;
    NSArray * _groups;
    NSString * _listenerName;
}

@end
