/* Generated by RuntimeBrowser
   Image: /usr/lib/libactivator.dylib
 */

@interface LARootSettingsController : LASettingsViewController {
    bool  alive;
    void * libhide;
    int (* libhideIsHidden;
    <LARootSettingsControllerDelegate> * rootSettingsDelegate;
    NSIndexPath * selectedIndexPath;
    bool  showsPersistentSelection;
}

@end
