/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PodcastsFoundation.framework/PodcastsFoundation
 */

@interface MTSecureDownloadRenewalManager : NSObject {
    void removalLock;
    void renewalLock;
    void secureKeyLoader;
    void urlProtocolDelegate;
    void workQueue;
}

+ (id)inContextKeyDataFor:(long long)arg1 ctx:(id)arg2;

- (void).cxx_destruct;
- (id)init;
- (id)initWithUrlProtocolDelegate:(id)arg1;
- (void)requestSecureDeletionOf:(long long)arg1;
- (void)willEnterForeground;

@end
