/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PodcastsFoundation.framework/PodcastsFoundation
 */

@interface PFSecureDownloadRenewalManager : NSObject {
    MTSecureDownloadRenewalManager * _manager;
}

+ (id)inContextKeyDataFor:(long long)arg1 ctx:(id)arg2;

- (void).cxx_destruct;
- (id)initWithURLProtocolDelegate:(id)arg1;
- (void)requestSecureDeletionOfEpisodeWithAdamID:(long long)arg1;
- (void)willEnterForeground;

@end
