/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.TodayTracker : _TtCs12_SwiftObject {
    void blueprintLayoutCollectionProvider;
    void blueprintLayoutProvider;
    void blueprintProvider;
    void channelDataFactory;
    void contentPrefetchManager;
    void hasRegisteredUserActivity;
    void headlineSeenQueue;
    void newsActivityManager;
    void scienceDataFactory;
    void sectionPositionProvider;
    void todayActivityRegistrationType;
    void tracker;
    void trackerConfiguration;
}

@end
