/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
 */

@interface MPCMediaRemoteCommandOperation : MPAsyncOperation {
    unsigned long long  _options;
    MPCPlayerCommandRequest * _request;
    MPCPlayerCommandStatus * _status;
}

@property (nonatomic, readonly) unsigned long long options;
@property (nonatomic, readonly) MPCPlayerCommandRequest *request;
@property (nonatomic, readonly) MPCPlayerCommandStatus *status;

- (void).cxx_destruct;
- (void)execute;
- (id)initWithCommandRequest:(id)arg1 options:(unsigned long long)arg2;
- (unsigned long long)options;
- (id)request;
- (id)status;

@end
