/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMDPersistence.framework/IMDPersistence
 */

@interface IMDCoreSpotlightContactCache : NSObject {
    NSMutableDictionary * _cache;
    NSObject<OS_dispatch_queue> * _contactCacheQueue;
    NSData * _currentHistoryToken;
}

@property (nonatomic, retain) NSMutableDictionary *cache;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *contactCacheQueue;
@property (nonatomic, retain) NSData *currentHistoryToken;

+ (id)contactsForVCardAtPath:(id)arg1;
+ (id)sharedInstance;
+ (void)updateAttributes:(id)arg1 withAddressFromContact:(id)arg2;
+ (void)vCardCoordinateForMapURL:(id)arg1 outLatitude:(float*)arg2 outLongitude:(float*)arg3;
+ (id)vCardMapURLForContact:(id)arg1;
+ (id)vCardNameForContact:(id)arg1;

- (id)cache;
- (void)cacheContact:(id)arg1 forKey:(id)arg2;
- (void)cacheContactsFromFetchResults:(id)arg1 forAliases:(id)arg2;
- (id)cachedContactForKey:(id)arg1 cacheHit:(bool*)arg2;
- (id)contactCacheQueue;
- (id)contactIDToAliasesMap;
- (void)contactStoreDidChange:(id)arg1;
- (id)currentHistoryToken;
- (void)dealloc;
- (id)init;
- (void)removeCachedContactForKey:(id)arg1;
- (void)resetCache;
- (void)setCache:(id)arg1;
- (void)setContactCacheQueue:(id)arg1;
- (void)setCurrentHistoryToken:(id)arg1;
- (void)updateCacheForAliases:(id)arg1;

@end
