/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSCampaignAttributionTask : AMSTask <AMSBagConsumer> {
    NSURL * _URL;
    ACAccount * _account;
    NSArray * _additionalQueryItems;
    <AMSBagProtocol> * _bag;
    AMSProcessInfo * _clientInfo;
    AMSURLSession * _urlSession;
}

@property (nonatomic, readonly) NSURL *URL;
@property (nonatomic, retain) ACAccount *account;
@property (nonatomic, copy) NSArray *additionalQueryItems;
@property (nonatomic, readonly) <AMSBagProtocol> *bag;
@property (nonatomic, retain) AMSProcessInfo *clientInfo;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, retain) AMSURLSession *urlSession;

+ (void)addRequiredBagKeysToAggregator:(id)arg1;
+ (id)bagKeySet;
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)createBagForSubProfile;

- (void).cxx_destruct;
- (id)URL;
- (id)_makeRequestEncoder;
- (id)_requestURLWithCampaignAttributionURL:(id)arg1;
- (void)_saveCookies:(id)arg1;
- (id)account;
- (id)additionalQueryItems;
- (id)bag;
- (id)clientInfo;
- (id)initWithURL:(id)arg1 bag:(id)arg2;
- (id)initWithURL:(id)arg1 bag:(id)arg2 urlSession:(id)arg3;
- (id)perform;
- (void)setAccount:(id)arg1;
- (void)setAdditionalQueryItems:(id)arg1;
- (void)setClientInfo:(id)arg1;
- (void)setUrlSession:(id)arg1;
- (id)urlSession;

@end
