/* Generated by RuntimeBrowser.
 */

@protocol _SFDialogPresenting <NSObject>

@required

- (WBSPermissionDialogThrottler *)permissionDialogThrottler;
- (void)presentDialog:(_SFDialog *)arg1 sender:(id)arg2;

@end
