/* Generated by RuntimeBrowser.
 */

@protocol CSSecondPassProgressProviding <NSObject>

@required

- (void)cancelSecondPassRunning;
- (void)fetchSecondPassState:(void *)arg1; // needs 1 arg types, found 8: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, NSString *, double, void*

@end
