/* Generated by RuntimeBrowser.
 */

@protocol HMDAssistantSettingsConnectionDataSource <NSObject>

@required

- (HMFOperation *)deleteSiriHistoryOperationWithConnection:(AFSettingsConnection *)arg1;

@end
