/* Generated by RuntimeBrowser.
 */

@protocol HMDAppleMediaAccessoryMessageRouterDataSource <NSObject>

@required

- (HMDDevice *)deviceForAppleMediaAccessoryMessageRouter:(HMDAppleMediaAccessoryMessageRouter *)arg1;

@end
