/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiomeStreams.framework/BiomeStreams
 */

@interface BMAppLaunchStream : NSObject <BMSourceStream, BMStream> {
    BMStoreStream * _storeStream;
}

@property (nonatomic, readonly) NSString *identifier;

// Image: /System/Library/PrivateFrameworks/BiomeStreams.framework/BiomeStreams

- (void).cxx_destruct;
- (id)identifier;
- (id)init;
- (id)publisherFromStartTime:(double)arg1;
- (id)source;

// Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal

- (id)rawLaunchCountAndDistinctDaysLaunchedOverLast28DaysForApps:(id)arg1;

@end
