/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAppleMediaAccessoryMessenger : HMFObject <HMFLogging, HMFMessageReceiver> {
    NSUUID * _identifier;
    HMDAppleMediaAccessoryLocalMessageHandler * _localHandler;
    HMFMessageDispatcher * _messageDispatcher;
    HMDAppleMediaAccessoryMessageRouter * _router;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly, copy) NSUUID *identifier;
@property (readonly) HMDAppleMediaAccessoryLocalMessageHandler *localHandler;
@property (readonly) HMFMessageDispatcher *messageDispatcher;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *messageReceiveQueue;
@property (nonatomic, readonly) NSUUID *messageTargetUUID;
@property (readonly) HMDAppleMediaAccessoryMessageRouter *router;
@property (readonly) Class superclass;

+ (id)logCategory;

- (void).cxx_destruct;
- (id)identifier;
- (id)initWithIdentifier:(id)arg1 messageDispatcher:(id)arg2 router:(id)arg3 localHandler:(id)arg4;
- (id)localHandler;
- (id)logIdentifier;
- (id)messageDispatcher;
- (id)messageTargetUUID;
- (void)registerForMessagesWithHome:(id)arg1;
- (id)router;

@end
