/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAccessoryMetricVendorDetails : HMFObject {
    NSString * _category;
    NSString * _firmwareVersion;
    NSString * _manufacturer;
    NSString * _model;
    NSString * _productData;
}

@property (nonatomic, copy) NSString *category;
@property (nonatomic, copy) NSString *firmwareVersion;
@property (nonatomic, copy) NSString *manufacturer;
@property (nonatomic, copy) NSString *model;
@property (nonatomic, copy) NSString *productData;

- (void).cxx_destruct;
- (id)category;
- (id)firmwareVersion;
- (id)initWithAccessory:(id)arg1;
- (id)manufacturer;
- (id)model;
- (id)productData;
- (void)setCategory:(id)arg1;
- (void)setFirmwareVersion:(id)arg1;
- (void)setManufacturer:(id)arg1;
- (void)setModel:(id)arg1;
- (void)setProductData:(id)arg1;

@end
