/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAssistantSettingsConnection : HMFObject <HMDAssistantSettingsConnectionDataSource, HMFLogging> {
    <HMDAssistantSettingsConnectionDataSource> * _dataSource;
    HMFScheduler * _scheduler;
}

@property <HMDAssistantSettingsConnectionDataSource> *dataSource;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) HMFScheduler *scheduler;
@property (readonly) Class superclass;

+ (id)logCategory;

- (void).cxx_destruct;
- (id)dataSource;
- (id)deleteSiriHistoryOperationWithConnection:(id)arg1;
- (id)initWithScheduler:(id)arg1;
- (id)scheduler;
- (void)setDataSource:(id)arg1;

@end
