/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDLogEventDispatcher : HMFObject <HMDLogEventSubmitting> {
    NSObject<OS_dispatch_queue> * _clientQueue;
    <HMFLocking> * _lock;
    NSMapTable * _logEventObserversByClass;
}

@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *clientQueue;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) HMDLogEventDispatcher *logEventDispatcher;
@property (nonatomic, readonly) NSMapTable *logEventObserversByClass;
@property (readonly) Class superclass;

+ (void)initialize;
+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)addObserver:(id)arg1 forEventClass:(Class)arg2;
- (void)addObserver:(id)arg1 forEventClasses:(id)arg2;
- (id)clientQueue;
- (id)init;
- (id)logEventObserversByClass;
- (void)removeObserver:(id)arg1 forEventClass:(Class)arg2;
- (void)submitLogEvent:(id)arg1;
- (void)submitLogEvent:(id)arg1 error:(id)arg2;

@end
