/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDRemoteEventRouterProtoConnectMessage : PBCodable <NSCopying> {
    HMEProtoEventInfo * _connectEvent;
    struct { 
        unsigned int routerVersion : 1; 
    }  _has;
    unsigned int  _routerVersion;
    NSMutableArray * _topicFilterAdditions;
    HMEProtoEventInfo * _unregisterEvent;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end
