/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDRemoteEventRouterProtoFragmentedMessage : PBCodable <NSCopying> {
    NSData * _fragmentData;
    unsigned int  _fragmentNumber;
    struct { 
        unsigned int totalFragments : 1; 
        unsigned int totalSize : 1; 
        unsigned int fragmentNumber : 1; 
        unsigned int routerVersion : 1; 
    }  _has;
    unsigned int  _routerVersion;
    unsigned long long  _totalFragments;
    unsigned long long  _totalSize;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end
