/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDRemoteEventRouterConnection : NSObject <HMEMessageDatagramConnection> {
    HMDDevice * _device;
    NSUUID * _deviceIdentifier;
    unsigned int  _routerVersion;
    <HMDRemoteEventRouterUserAccessControlProvider> * _userAccessControlProvider;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;

@end
