/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoordinationCore.framework/CoordinationCore
 */

@interface COMeshNodeStateTracker : NSObject {
    COBallot * _ballot;
    <COMeshNodeStateTrackerDelegate> * _delegate;
    unsigned long long  _generation;
    double  _lastHeard;
    COMeshNode * _node;
    bool  _outstandingProbe;
    unsigned long long  _state;
    long long  _status;
}

@property (nonatomic, copy) COBallot *ballot;
@property (nonatomic) <COMeshNodeStateTrackerDelegate> *delegate;
@property (nonatomic) unsigned long long generation;
@property (nonatomic) double lastHeard;
@property (nonatomic, readonly) COMeshNode *node;
@property (getter=hasOutstandingProbe, nonatomic) bool outstandingProbe;
@property (nonatomic) unsigned long long state;
@property (nonatomic) long long status;

- (void).cxx_destruct;
- (id)ballot;
- (id)delegate;
- (id)description;
- (unsigned long long)generation;
- (bool)hasOutstandingProbe;
- (id)initWithNode:(id)arg1;
- (double)lastHeard;
- (id)node;
- (void)setBallot:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setGeneration:(unsigned long long)arg1;
- (void)setLastHeard:(double)arg1;
- (void)setOutstandingProbe:(bool)arg1;
- (void)setState:(unsigned long long)arg1;
- (void)setStatus:(long long)arg1;
- (unsigned long long)state;
- (long long)status;

@end
