/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoordinationCore.framework/CoordinationCore
 */

@interface COMeshControllerQueuedCommand : NSObject <COMeshControllerQueuedElementProtocol> {
    id /* block */  _callback;
    COMeshCommand * _command;
    COMeshNode * _destination;
}

@property (nonatomic, readonly, copy) id /* block */ callback;
@property (nonatomic, readonly) COMeshCommand *command;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) COMeshNode *destination;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id /* block */)callback;
- (id)command;
- (id)destination;
- (id)initWithCommand:(id)arg1 sentCallback:(id /* block */)arg2;
- (void)invokeCallbackWithError:(id)arg1;
- (void)setDestination:(id)arg1;

@end
