/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriVideoIntents.framework/SiriVideoIntents
 */

@interface Content : INObject

@property (nonatomic, copy) NSURL *detailsUrl;
@property (nonatomic, copy) NSString *episodeNumber;
@property (nonatomic, copy) NSDate *finaleDate;
@property (nonatomic, copy) NSString *genre;
@property (nonatomic, copy) NSNumber *hasMoreResults;
@property (nonatomic, copy) NSArray *images;
@property (nonatomic, copy) NSNumber *isInWatchList;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSURL *punchoutUrl;
@property (nonatomic, copy) NSDate *releaseDate;
@property (nonatomic, copy) Content *season;
@property (nonatomic, copy) NSNumber *seasonCount;
@property (nonatomic, copy) NSString *seasonNumber;
@property (nonatomic, copy) Content *show;
@property (nonatomic, copy) NSNumber *type;
@property (nonatomic, copy) NSString *umcId;
@property (nonatomic, copy) NSString *utsSearchUrl;

@end
