/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriVideoIntents.framework/SiriVideoIntents
 */

@interface ImageTypeResolutionResult : INEnumResolutionResult

+ (id)confirmationRequiredWithImageTypeToConfirm:(long long)arg1;
+ (id)successWithResolvedImageType:(long long)arg1;

@end
