/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriVideoIntents.framework/SiriVideoIntents
 */

@interface PlayVideoIntent : INIntent

@property (nonatomic, copy) Content *content;
@property (nonatomic, copy) ContentSearch *contentSearch;
@property (nonatomic, copy) NSArray *suggestedContent;

@end
