/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/LimitAdTracking.framework/LimitAdTracking
 */

@interface ADTrackingTransparency : NSObject

@property (nonatomic) bool crossAppTrackingAllowed;
@property (nonatomic, readonly) long long crossAppTrackingAllowedSwitchDisabledReason;
@property (nonatomic, readonly) bool crossAppTrackingAllowedSwitchEnabled;
@property (nonatomic) bool personalizedAds;
@property (nonatomic, readonly) bool personalizedAdsAvailable;
@property (nonatomic, readonly) long long personalizedAdsSwitchDisabledReason;
@property (nonatomic, readonly) bool personalizedAdsSwitchEnabled;

- (bool)_isUserEDURestricted;
- (bool)_isUserManagedRestricted;
- (bool)_userAllowedToChangeSettings;
- (long long)accountLevelSwitchDisabledReason;
- (long long)accountRestrictionReason;
- (id)appTrackingServiceProxy:(id)arg1;
- (id)appTrackingXPCConnection:(id /* block */)arg1 withInvalidation:(id /* block */)arg2;
- (bool)crossAppTrackingAllowed;
- (long long)crossAppTrackingAllowedSwitchDisabledReason;
- (bool)crossAppTrackingAllowedSwitchEnabled;
- (bool)isPersonalizedAdsScreenTimeRestricted;
- (bool)personalizedAds;
- (bool)personalizedAdsAvailable;
- (void)personalizedAdsAvailable:(id /* block */)arg1;
- (long long)personalizedAdsSwitchDisabledReason;
- (bool)personalizedAdsSwitchEnabled;
- (void)setCrossAppTrackingAllowed:(bool)arg1;
- (void)setPersonalizedAds:(bool)arg1;
- (bool)shouldDisplayPAUI;

@end
