/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Announce.framework/Announce
 */

@interface ANUtils : NSObject

+ (bool)isInternalBuild;
+ (double)machTimeToSeconds:(unsigned long long)arg1;
+ (unsigned long long)secondsToMachTime:(double)arg1;

@end
