/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXOnboardingStackWidgetCache : NSObject <NSCopying, NSSecureCoding> {
    NSDate * _cacheUpdateDate;
    NSDictionary * _descriptorToAppLaunchData;
}

@property (nonatomic, readonly) NSDate *cacheUpdateDate;
@property (nonatomic, readonly) NSDictionary *descriptorToAppLaunchData;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)cacheUpdateDate;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)descriptorToAppLaunchData;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithAppLaunchDictionary:(id)arg1;
- (id)initWithAppLaunchDictionary:(id)arg1 cacheUpdateDate:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;

@end
