/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUARP.framework/CoreUARP
 */

@interface UARPSupportedAccessoryManager : NSObject {
    NSMutableSet * _setOfAccessories;
}

@property (readonly) NSSet *setOfAccessories;

+ (id)defaultManager;

- (void).cxx_destruct;
- (void)addSupportedAccessories:(id)arg1;
- (void)addSupportedAccessory:(id)arg1;
- (id)init;
- (id)setOfAccessories;

@end
