/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOAnalyticsPipelineSharedStateData : GEOAnalyticsPipelineStateData {
    geo_isolater * _mapViewIso;
    geo_isolater * _placeIso;
}

+ (id)sharedData;

- (void).cxx_destruct;
- (bool)_hasActualFallbackMetro;
- (bool)_hasActualUserHomeCountry;
- (bool)_hasActualUserHomeMetro;
- (bool)_isHandoff;
- (bool)_isHandoffFromDeviceType:(id)arg1;
- (id)_metroForLatLng:(id)arg1 inCountry:(id)arg2 filterWithAllowList:(bool)arg3;
- (void)_performSyncStateUpdateWithIsolator:(id)arg1 updateBlock:(id /* block */)arg2;
- (void)_populateWithGEOTransitDepartureSequenceUsage:(id)arg1;
- (void)_populateWithGEOTransitPlaceCard:(id)arg1;
- (int)activeNavModeAsGEOTransportType;
- (id)bestCurrentMetro;
- (id)bestUserHomeCountry;
- (id)bestUserHomeMetro;
- (void)clearPlaceCardStateData;
- (void)clearSuggestionsData;
- (bool)hasMapLaunchData;
- (bool)hasMapRestoreData;
- (bool)hasMapsServerData;
- (bool)hasPlaceCardStateData;
- (bool)hasPlaceCard_PlaceActionDetails;
- (bool)hasPlaceCard_PlaceActionDetails_TransitPlaceCard;
- (bool)hasPlaceCard_PlaceActionDetails_TransitPlaceCard_TransitDepartureSequence;
- (bool)hasSuggestionsData;
- (id)init;
- (bool)isIPadHandoff;
- (bool)isIPhoneHandoff;
- (bool)isMacHandoff;
- (bool)isWatchHandoff;
- (int)layoutInfoAsGEOLayoutInfo;
- (int)layoutStyleAsGEOLayoutStyle;
- (int)locationPrecisionTypeAsGEOSettingsLocationType;
- (int)navVoiceVolumeAsGEONavVoiceVolume;
- (void)performMapViewStateUpdate:(id /* block */)arg1;
- (void)performPlaceCardStateUpdate:(id /* block */)arg1;
- (void)populateWithChildPlace:(id)arg1 timestamp:(double)arg2 resultIndex:(int)arg3;
- (void)populateWithPlace:(id)arg1 timestamp:(double)arg2 resultIndex:(int)arg3;
- (void)populateWithPlaceActionDetails:(id)arg1;
- (void)setCurrentMetro:(id)arg1;
- (void)setMeCardHomeCountry:(id)arg1 andHomeLocation:(id)arg2;
- (int)transportModeAsGEOTransportMode;

@end
