/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOAnalyticsPipelineNewSessionStartDates : PBCodable <NSCopying> {
    NSMutableArray * _sessions;
}

@property (nonatomic, retain) NSMutableArray *sessions;

+ (bool)isValid:(id)arg1;
+ (Class)sessionsType;

- (void).cxx_destruct;
- (void)addSessions:(id)arg1;
- (void)clearSessions;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonRepresentation;
- (void)mergeFrom:(id)arg1;
- (void)readAll:(bool)arg1;
- (bool)readFrom:(id)arg1;
- (id)sessions;
- (id)sessionsAtIndex:(unsigned long long)arg1;
- (unsigned long long)sessionsCount;
- (void)setSessions:(id)arg1;
- (void)writeTo:(id)arg1;

@end
