/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOAnalyticsPipelineSessionAndStartDate : PBCodable <NSCopying> {
    struct { 
        unsigned int has_session : 1; 
        unsigned int has_startDate : 1; 
    }  _flags;
    struct GEOSessionID { 
        unsigned long long _high; 
        unsigned long long _low; 
    }  _session;
    unsigned long long  _startDate;
}

@property (nonatomic) bool hasSession;
@property (nonatomic) bool hasStartDate;
@property (nonatomic) struct GEOSessionID { unsigned long long x1; unsigned long long x2; } session;
@property (nonatomic) unsigned long long startDate;

+ (bool)isValid:(id)arg1;

- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasSession;
- (bool)hasStartDate;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonRepresentation;
- (void)mergeFrom:(id)arg1;
- (void)readAll:(bool)arg1;
- (bool)readFrom:(id)arg1;
- (struct GEOSessionID { unsigned long long x1; unsigned long long x2; })session;
- (void)setHasSession:(bool)arg1;
- (void)setHasStartDate:(bool)arg1;
- (void)setSession:(struct GEOSessionID { unsigned long long x1; unsigned long long x2; })arg1;
- (void)setStartDate:(unsigned long long)arg1;
- (unsigned long long)startDate;
- (void)writeTo:(id)arg1;

@end
